# Data Configuration
num_workers: 0
seed: 42
train_split: 0.8

# Model Configuration
model_backbone: "cnn"  # "dense"
input_dim: 784
image_dim: 28
num_channels: 1
num_classes: 3

# Training Parameters
batch_size: 16
learning_rate: 0.001
max_epochs: 20
load_from_ckpt: False

# Label Mappings
target_labels: [0, 5, 8]

# Test Configuration
data_dir: "data/"
output_dir: "checkpoints"

# Email configuration
EMAIL_ADDRESS: 'ariannampryor@gmail.com'
EMAIL_PASSWORD: 'znuc qktb woyl toxy'  # need to set this up
SMTP_SERVER: 'smtp.gmail.com'
SMTP_PORT: 587