# Data Configuration
seed: 42
train_split: 0.8
target_labels: [0, 5, 8]
num_classes: 3

# Model Configuration
use_cnn: True
num_channels: 1
input_dim: 784 # only needed for dense network
image_dim: 28  # only for test evaluation

# Training Parameters
batch_size: 32
learning_rate: 0.001
max_epochs: 20
load_from_ckpt: False


# Test Configuration
data_dir: "data/"
output_dir: "checkpoints"

# Email configuration
EMAIL_ADDRESS: 'ariannampryor@gmail.com'
EMAIL_PASSWORD: 'znuc qktb woyl toxy'  # need to set this up
SMTP_SERVER: 'smtp.gmail.com'
SMTP_PORT: 587