batch_size: 32
learning_rate: 0.001
max_epochs: 20

load_from_ckpt: False

# Email configuration
EMAIL_ADDRESS: 'ariannampryor@gmail.com'
EMAIL_PASSWORD: 'znuc qktb woyl toxy'  # need to set this up
SMTP_SERVER: 'smtp.gmail.com'
SMTP_PORT: 587